name: Build Test

on:
  push:
    branches:
    - MiraiCQ-Cli
    paths:
    - .github/workflows/**
    - src/**

jobs:
  test:
    name: build project
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
    - name: MSBuild
      run: |
        cd src/MiraiCQ
        msbuild /property:Configuration=Release
        del Release/*.exp
        del Release/*.pdb
        del Release/MiraiCQ.lib
    - name: upload file
      uses: actions/upload-artifact@v2
      with:
        name: upload files
        path: 
            src/MiraiCQ/Release
